version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    restart: always
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_PORT=27017
    command: >
      sh -c "sleep 10 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 5s

networks:
  app_network:
    driver: bridge
